### ISSUE TITLE
Arc Consistency Problem fixed.

### ISSUE THREAD

**Issue by ZijiaZhang99** [AISpace2/AISpace2#40]
Fixed the Bug that clicking on arcs will not do anything.

Replacing:
`other_vars = [ov for ov in const.scope if ov is not var]`
with
`other_vars = [ov for ov in const.scope if ov != var]`
at line 32 in the first code cell in arc_consistency.ipynb

I don't have the permission to create new branch.

**Comment by davpoole** [comment]
An arc should be blue if it is on the to_do list, green otherwise. Someone should be able to click on a blue arc to make it arc consistent.
Someone should be able to click on a domain to split it when network is arc consistent. We need a way to tell a user what they can do. E.g., if they click on a node when it the network has not been made arc consistent,  we need a way to tell them what is happening.
